###
GET http://localhost:3001/admin/products

###
# @name createProduct
POST http://localhost:3001/admin/products
Content-Type: application/json

{
    "name": "Product 2",
    "slug": "product-2",
    "description": "Product 2 description",
    "price": 5.99
}

###

@productId = {{ createProduct.response.body.id }}

GET http://localhost:3001/admin/products/111

###

PATCH http://localhost:3001/admin/products/cm84ubno900000xcxdgfhff3r
Content-Type: application/json

{
    "name": "Product 222",
    "slug": "product-xpto",
    "description": "Product 222 description",
    "price": 5.90
}
###
DELETE http://localhost:3001/admin/products/{{productId}}

###
GET http://localhost:3001/products?name=1

###
GET http://localhost:3001/products/product-1